# Generated by Django 5.1.3 on 2024-11-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('DeveloperID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Developer',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Viewer',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeveloperName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.developer')),
                ('ViewerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.viewer')),
            ],
            options={
                'verbose_name': 'Admin',
            },
        ),
    ]
