# Generated by Django 5.1.3 on 2024-11-19 06:08

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name_plural': 'Developer'},
        ),
        migrations.AlterModelOptions(
            name='viewer',
            options={'verbose_name_plural': 'Viewer'},
        ),
        migrations.AlterField(
            model_name='developer',
            name='DeveloperID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='number',
            field=models.BigIntegerField(unique=True, validators=[Myapp.models.validate_number]),
        ),
    ]
