# Generated by Django 5.1.3 on 2024-11-19 06:14

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_developer_options_alter_viewer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterField(
            model_name='developer',
            name='DeveloperID',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[Myapp.models.validate_developer]),
        ),
    ]
