# Generated by Django 5.1.3 on 2024-11-19 08:22

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_viewer_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='number',
            field=models.BigIntegerField(unique=True, validators=[Myapp.models.validate_number]),
        ),
    ]
