# Generated by Django 5.1.3 on 2024-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_alter_viewer_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewer',
            old_name='otp',
            new_name='generated_otp',
        ),
        migrations.AddField(
            model_name='viewer',
            name='user_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
