# Generated by Django 5.1.3 on 2024-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_rename_otp_viewer_generated_otp_viewer_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='role',
            field=models.CharField(default='Viewer', editable=False, max_length=20),
        ),
    ]
