# Generated by Django 5.1.3 on 2024-11-22 15:41

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_viewerbehaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_viewer', models.CharField(max_length=50)),
                ('email_viewer', models.EmailField(max_length=100)),
                ('number_viewer', models.BigIntegerField(unique=True, validators=[Myapp.models.validate_number])),
                ('reason', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Viewer -> Admin : Form Submission',
            },
        ),
        migrations.AlterModelOptions(
            name='viewerbehaviour',
            options={'verbose_name_plural': 'Viewer Behaviour'},
        ),
    ]
