# Generated by Django 5.1.3 on 2024-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_viewer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
